export const cards = [
  {
    id: '1',
    vendor: 'Techne',
    price: '12 700',
    src: './img/watch_1.png',
    mechanism: 'mechanic',
    material: 'metal',
    color: 'green',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '2',
    vendor: 'Rado',
    price: '13 900',
    src: './img/watch_2.png',
    mechanism: 'quartz',
    material: 'plastic',
    color: 'brown',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '3',
    vendor: 'Bvlgari',
    price: '18 700',
    src: './img/watch_3.png',
    mechanism: 'mechanic',
    material: 'metal',
    color: 'red',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '4',
    vendor: 'Tissot',
    price: '18 700',
    src: './img/watch_3.png',
    mechanism: 'quartz',
    material: 'plastic',
    color: 'red',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '5',
    vendor: 'Omega',
    price: '50 700',
    src: './img/watch_4.png',
    mechanism: 'mechanic',
    material: 'metal',
    color: 'black',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '6',
    vendor: 'Tissot',
    price: '79 300',
    src: './img/watch_5.png',
    mechanism: 'quartz',
    material: 'plastic',
    color: 'brown',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '7',
    vendor: 'Montblanc',
    price: '80 000',
    src: './img/watch_6.png',
    mechanism: 'mechanic',
    material: 'metal',
    color: 'brown',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '8',
    vendor: 'Techne',
    price: '100 000',
    src: './img/watch_7.png',
    mechanism: 'quartz',
    material: 'plastic',
    color: 'red',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '9',
    vendor: 'Rado',
    price: '33 200',
    src: './img/watch_8.png',
    mechanism: 'mechanic',
    material: 'metal',
    color: 'black',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '10',
    vendor: 'Bvlgari',
    price: '42 100',
    src: './img/watch_9.png',
    mechanism: 'quartz',
    material: 'plastic',
    color: 'black',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '11',
    vendor: 'Tissot',
    price: '50 000',
    src: './img/watch_10.png',
    mechanism: 'mechanic',
    material: 'metal',
    color: 'red',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '12',
    vendor: 'Omega',
    price: '53 300',
    src: './img/watch_11.png',
    mechanism: 'mechanic',
    material: 'plastic',
    color: 'black',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '13',
    vendor: 'Montblanc',
    price: '66 300',
    src: './img/watch_1.png',
    mechanism: 'mechanic',
    material: 'metal',
    color: 'green',
    mechanismChecked: true,
    vendorChecked: true,
    materialChecked: true,
    colorChecked: true,
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
];

export const straps = [
  {
    id: '14',
    vendor: 'Georg Jensen',
    price: '6 500',
    src: '/img/band1.png',
    material: 'leather',
    color: 'brown',
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '15',
    vendor: 'Nato',
    price: '3 200',
    src: '/img/band2.png',
    material: 'leather',
    color: 'black',
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '16',
    vendor: 'Spark',
    price: '5 400',
    src: '/img/band3.png',
    material: 'leather',
    color: 'yellow',
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '17',
    vendor: 'Gentleman',
    price: '8 100',
    src: '/img/band1.png',
    material: 'leather',
    color: 'brown',
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '18',
    vendor: 'Black Arrow',
    price: '6 600',
    src: '/img/band2.png',
    material: 'leather',
    color: 'black',
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
  {
    id: '19',
    vendor: 'Fantasy',
    price: '2 600',
    src: '/img/band3.png',
    material: 'leather',
    color: 'yellow',
    addToCartFetching: false,
    inCart: false,
    addToFavoritesFetching: false,
    inFavorites: false,
    uniqueId: '',
    uniqueFavoritesId: '',
  },
];

export const colors = {
  black: 'чёрный',
  brown: 'коричневый',
  green: 'зелёный',
  red: 'красный',
};

export const materials = {
  metal: 'метал',
  plastic: 'пластик',
  leather: 'кожа',
};

export const mechanisms = {
  mechanic: 'механика',
  quartz: 'кварц',
};

export const endpoints = {
  watchCatalog: 'watch-catalog',
  strapCatalog: 'strap-catalog',
};

export const cartTypes = {
  product: 'product',
  favorites: 'favorites',
};
